ViennaRNA-2.4.17
ComputeCanada/easybuild-easyconfigs pull request #19
Opened 2021-03-11 00:54 UTC by JLague

2021-03-11 01:05 UTC, ccoulombe commented on easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.4.17-GCCcore-9.3.0.eb
> +multi_deps = {"Python": ["2.7", "3.6", "3.7", "3.8"]}
Python 2 est mort, on peut le laisser mort. Nul besoin de le supporter.

2021-03-11 01:09 UTC, ccoulombe requested changes

2021-03-11 01:09 UTC, ccoulombe commented on easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.4.17-GCCcore-9.3.0.eb
> +sanity_check_paths = {
Ajouter une validation que le path pour le site-packages existe bel et bien

2021-03-11 01:09 UTC, ccoulombe commented on easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.4.17-GCCcore-9.3.0.eb
> +
`sanity_check_commands` pour tester que le import fonctionne correctement

2021-03-11 18:45 UTC, JLague commented on easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.4.17-GCCcore-9.3.0.eb
> +multi_deps = {"Python": ["2.7", "3.6", "3.7", "3.8"]}
La seule raison pourquoi Python 2 a été inclut est parce que ViennaRNA le supporte. Je vais l'enlever.

2021-03-11 21:35 UTC, JLague commented on easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.4.17-GCCcore-9.3.0.eb
> +sanity_check_paths = {
Validation du path ajoutée

2021-03-11 21:35 UTC, JLague commented on easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.4.17-GCCcore-9.3.0.eb
> +
Test d'import ajouté.

2021-03-12 13:42 UTC, ccoulombe requested changes

2021-03-12 13:42 UTC, ccoulombe commented on easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.4.17-GCCcore-9.3.0.eb
> +
Le footer a disparu? Puisque ce module, à ma connaissance, est régulièrement utilisé en Python, il serait pertinent de remettre le footer qui force la dépendance sur le python par défaut.

2021-03-12 16:08 UTC, JLague commented on easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.4.17-GCCcore-9.3.0.eb
> +
Remis le modluafooter

2021-03-12 16:12 UTC, ccoulombe approved these changes
All good!

2021-03-12 16:12 UTC, merged