Fix building PRIMME with ebuser which does not find primme.h header
ComputeCanada/easybuild-easyconfigs pull request #72
Opened 2023-11-02 20:36 UTC by MoiseRousseau

- Fix building by ebuser which can't find primme.h header.
- Make a patch instead of doing sed

2023-11-02 20:43 UTC, ccoulombe requested changes
Le fichier de patch doit suivre la nomenclature de la config : `PRIMME-3.2-fix-include-python.patch`

2023-11-06 10:34 UTC, ccoulombe requested changes
Update checksum and patche name

2023-11-07 18:12 UTC, MoiseRousseau commented
> Update checksum and patche name

Patch name changed. Checksum is the same.

2023-11-07 18:27 UTC, ccoulombe approved these changes

2023-11-07 18:27 UTC, merged