Fix KaHyPar recipe
ComputeCanada/easybuild-easyconfigs pull request #78
Opened 2023-12-04 17:10 UTC by MoiseRousseau

There was AVX512 instruction in the AVX2 version installed, because the -march=native flag was defined in the compilation. Fix the CMakeLists.txt in a patch.

2023-12-04 17:21 UTC, ccoulombe requested changes
Are you certain that it does not hinder its compilation? for example, is there other compilation flags that are removed?

2023-12-04 17:21 UTC, ccoulombe commented on easybuild/easyconfigs/k/KaHyPar/KaHyPar-1.3.2_fix_install.patch
> +-    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -mtune=native -march=native")
Normally, you would just remove the `-mtune=native -march=native`

2023-12-06 15:05 UTC, MoiseRousseau commented on easybuild/easyconfigs/k/KaHyPar/KaHyPar-1.3.2_fix_install.patch
> +-    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -mtune=native -march=native")
There is already the -O2 optimisation flag by default, shouldn't it ? I was told the -O3 is too agressive sometimes, so I remove the entire line. Note this have been tested with success on AVX2 processors.

2023-12-06 18:42 UTC, ccoulombe approved these changes
:+1:

2023-12-06 18:42 UTC, merged