Add Qiskit dependencies for StdEnv/2020
ComputeCanada/easybuild-easyconfigs pull request #80
Opened 2024-01-12 13:49 UTC by MoiseRousseau

Add cuQuantum, muparserx recipes and update Python extension for SymEngine. Required to build Qiskit-AER simulator for StdEnv/2023.

2024-01-12 15:33 UTC, mboisson commented
Il faut probablement installer cuQuantum dans le dépôt restricted, @bartoldeman, peux-tu reviewer ?

2024-01-12 19:53 UTC, MoiseRousseau commented
Je vous laisse voir ça entre vous ou avec mon successeur ? Je quitte CQ à la fin de la journée :)

2024-01-15 14:40 UTC, ccoulombe requested changes
Les bindings 0.11 ne fonctionnent pas et n'étaient pas compatible, c'est pour cela que j'avais utilisé 0.10, qui étaient compatible

2025-01-29 18:59 UTC, ccoulombe commented
Nous avons v24 sous 2023 maintenant

2025-01-29 18:59 UTC, closed without merging